name: tus_client
description: A tus client for dart allowing resumable uploads using the tus protocol.
version: 1.0.4
homepage: https://github.com/jjmutumi/tus_client

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.3+4
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
